config:
  existingSecret: console-env-vars
  
  platform:
    external:
      url: https://console.k8s.tutorial

  organization:
    name: 'Conduktor Demo'

  admin:
    email: 'admin@demo.dev'

  database:
    host: 'postgresql'
    port: 5432
    name: 'postgres'

  clusters:
    - id: my-local-kafka-cluster
      name: My Local Kafka Cluster
      color: '#0013E7'
      bootstrapServers: 'franz-kafka.conduktor.svc.cluster.local:9092'
    - id: conduktor-gateway
      name: Conduktor Gateway
      color: '#FF0000'
      bootstrapServers: 'gateway.k8s.tutorial:9092'
      kafkaFlavor:
        type: Gateway
        url: https://gateway.k8s.tutorial
        user: admin
        password: conduktor
        virtualCluster: passthrough
        ignoreUntrustedCertificate: true

platform:
  extraVolumes:
    - name: truststore
      secret:
        secretName: gateway-cert
        items:
        - key: kafka.truststore.jks
          path: kafka.truststore.jks

  extraVolumeMounts:
    - name: truststore
      mountPath: /etc/gateway/tls/truststore/
      readonly: true


# Cortex configuration override from configmap
# platformCortex:
#   extraVolumes: 
#     - name: cortex-config-override
#       configMap:
#         name: conduktor-console-cortex-config
#   extraVolumeMounts:
#         - name: cortex-config-override
#           subPath: cortex.yaml # key in configmap to use as file contents
#           mountPath: /opt/override-configs/cortex.yaml # path to file in Cortex container
#         - name: cortex-config-override
#           subPath: prometheus.yaml
#           mountPath: /opt/override-configs/prometheus.yaml
